channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - pip
  - pip:
    - -e .[dev]
    # .  # bare minimum
    # - .[dev,jupyter,jax,data,misc]  # include all optional dependencies
    # - -e .[dev,jupyter,jax,data,misc]  # optional dependencies in editing mode
